// Auto-generated by LibreLane
module spi_adc(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input sys_clk,
  input reset_,
  input cs,
  input sck,
  input mosi,
  output miso,
  input comparator,
  output[11:0] dac,
  output sample_and_hold,
  output pwr_gate,
  output dac_rst,
  output irq,
  output vref_sel,
  output adc_clk_out
);
endmodule
